version: '3.1'
services:
  schedule:
    network_mode: bridge
    container_name: schedule
    image: andrewdarialov/schedulecontroller:latest
    build: ./
    ports:
      - "8888:8888"
    environment:
      - POSTGRES_PASSWORD=44680339Aa!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=schedule
      - DB_SERVER=postgresqldb-schedule
    links:
      - postgresqldb-schedule

  postgresqldb-schedule:
    network_mode: bridge
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=44680339Aa!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=schedule
    volumes:
      - postgres-data-schedule:D:\volumes\scheduleService
volumes:
  postgres-data-schedule: